Repository Studio-Yandex-Practicum/Goodstart_telegram_bot, pull requests merged in 2024-06, with the labels that each got.

#101 Add FSM guidance to Readme
  README.md
Labels: documentation

#131 Feature/merge template schedule
  src/bot/bot_interface.py
  src/core/config/settings_base.py
  src/schooling/utils.py
  src/schooling/views.py
  src/staticfiles/scripts/accordion-schedule.js
  src/staticfiles/styles/accordion-schedule.css
  src/templates/schedule/base.html
  src/templates/schedule/day_schedule.html
  src/templates/schedule/includes/footer.html
  src/templates/schedule/includes/header.html
  src/templates/schedule/includes/schedule_day_card.html
  src/templates/schedule/pages/accordion-schedule.html
  src/templates/schedule/schedule.html
  src/templates/schedule/schedule_lessons.html
Labels: bug

#143 Убрать сохранение заявок из админки
  src/potential_user/admin.py
Labels: enhancement
